#!/usr/bin/env python3
"""Convert ngspice .raw (binary or ascii) to .vcd for GTKWave."""

import sys
import struct
import re

def parse_raw(path):
    with open(path, 'rb') as f:
        data = f.read()

    # Split header (text) from binary data at "Binary:\n"
    marker = b'Binary:\n'
    idx = data.find(marker)
    is_binary = idx != -1
    if not is_binary:
        marker = b'Values:\n'
        idx = data.find(marker)

    header_text = data[:idx].decode('ascii', errors='replace')
    body = data[idx + len(marker):]

    n_vars = int(re.search(r'No\. Variables:\s*(\d+)', header_text).group(1))
    n_points = int(re.search(r'No\. Points:\s*(\d+)', header_text).group(1))

    var_lines = re.findall(r'^\s*\d+\s+(\S+)\s+(\S+)', header_text, re.MULTILINE)
    var_names = [v[0] for v in var_lines][:n_vars]
    var_types = [v[1] for v in var_lines][:n_vars]

    values = [[] for _ in range(n_vars)]

    if is_binary:
        rec_size = n_vars * 8  # real values, 8 bytes each (double)
        for p in range(n_points):
            offset = p * rec_size
            chunk = body[offset:offset + rec_size]
            if len(chunk) < rec_size:
                break
            for v in range(n_vars):
                val = struct.unpack_from('<d', chunk, v * 8)[0]
                values[v].append(val)
    else:
        text = body.decode('ascii', errors='replace')
        rows = re.split(r'\n(?=\s*\d+\s)', text.strip())
        for row in rows:
            nums = re.findall(r'[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?', row)
            nums = nums[1:]  # skip point index
            for v in range(n_vars):
                if v < len(nums):
                    values[v].append(float(nums[v]))

    return var_names, var_types, values, n_points


def write_vcd(path, var_names, var_types, values, n_points):
    # Assign short VCD identifiers
    ids = {}
    chars = "!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    for i, name in enumerate(var_names):
        ids[name] = chars[i % len(chars)]

    time_idx = var_names.index('time') if 'time' in var_names else 0

    with open(path, 'w') as f:
        f.write("$date\n    generated by raw2vcd\n$end\n")
        f.write("$timescale 1ns $end\n")
        f.write("$scope module top $end\n")
        for name in var_names:
            if name == 'time':
                continue
            safe_name = name.replace('(', '_').replace(')', '')
            f.write(f"$var real 64 {ids[name]} {safe_name} $end\n")
        f.write("$upscope $end\n$enddefinitions $end\n")

        for p in range(n_points):
            t_seconds = values[time_idx][p]
            t_ns = t_seconds * 1e9
            f.write(f"#{int(t_ns * 1000)}\n")  # ps resolution
            for v, name in enumerate(var_names):
                if name == 'time':
                    continue
                f.write(f"r{values[v][p]:.10g} {ids[name]}\n")


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} input.raw output.vcd")
        sys.exit(1)

    var_names, var_types, values, n_points = parse_raw(sys.argv[1])
    print(f"Parsed {len(var_names)} variables, {n_points} points: {var_names}")
    write_vcd(sys.argv[2], var_names, var_types, values, n_points)
    print(f"Wrote {sys.argv[2]}")